Updated
IEEE-VIT/hackfest-flutter pull request #54
Opened 2023-10-13 04:23 UTC by shirshakk

# Story Title

[Design: UI revamp of search, contributors and about-us tabs](https://github.com/IEEE-VIT/hacktoberfest-flutter/issues/43)

## Changes made

-   make changes on contribution page , home_page and info_page
-   improve the ui and interconnectivity of the page

## How does the solution address the problem

This PR will give the information about all the contributor , provide the feature to the user to input the new contributor . In aboutUs page it will give the information about the hacktoberfest when clicked on the image and also provide the information IEEE information in the same way
## Linked issues

Resolves #1

2023-10-13 05:45 UTC, dk-a-dev commented
@shirshakk we have added flutter lint rules with a new commit, please pull that commit and make sure to optimise and refactor your code before putting up any commits as per lint rules, your code editor will help u out in code improvement, by giving warnings make sure to fix them

2023-10-13 05:58 UTC, dk-a-dev commented on lib/main.dart
Splash screen ??
Remove the splash screen, this issue does not intend to add or change the splash screen, also a dedicated screen(file) for splash is there, please stick to dedicated requirement

2023-10-13 06:09 UTC, dk-a-dev commented on pubspec.yaml
> -    - assets/
this is fine no need to put individual files names here, just putting up folder path will be enough

2023-10-13 06:13 UTC, dk-a-dev commented on lib/screens/contributors.dart
Good job fixing the contributors page but, I suggest you upgrade Flutter version and also adopt good practices, like adding the const keyword wherever required
but first things first "flutter upgrade" do an upgrade

2023-10-13 06:14 UTC, dk-a-dev commented on lib/screens/contributors.dart
> +  if (await canLaunch(url)) {
![image](https://github.com/IEEE-VIT/hacktoberfest-flutter/assets/84137299/07846619-6e6f-4c21-86e2-7583a2569782)

Please stick to newer methods and functions

2023-10-13 06:19 UTC, dk-a-dev commented on lib/screens/contributors.dart
> +  const Contributors({Key? key});
![image](https://github.com/IEEE-VIT/hacktoberfest-flutter/assets/84137299/d82da88b-7e6d-4fd9-9e39-442f17325e4d)

Fix: refer left comment

2023-10-13 06:19 UTC, dk-a-dev commented on lib/screens/contributors.dart
> -  const Contributors({super.key});
> const Contributors({super.key});

this is absolutely modern way to do this using super keyword
again migrate to newer versions of flutter and dart

2023-10-13 06:20 UTC, dk-a-dev commented on lib/screens/contributors.dart
> +          title: Text('Add Contributor'),
![image](https://github.com/IEEE-VIT/hacktoberfest-flutter/assets/84137299/d437088d-e7a1-4332-bff6-caa4eb622238)

use const keyword for every widget which avoids unnecessary rebuilds

2023-10-13 06:31 UTC, dk-a-dev commented on lib/screens/contributors.dart
>    Widget build(BuildContext context) {
This method overrides a method annotated as '@mustCallSuper' in 'AutomaticKeepAliveClientMixin', but doesn't invoke the overridden method.

fix: super.build(context); after line 44

2023-10-13 06:33 UTC, dk-a-dev commented on lib/screens/contributors.dart
> +    try {
Using BuildContexts across async functions is bad practice see if u can refactor code and avoid it

2023-10-13 06:34 UTC, dk-a-dev commented on lib/screens/contributors.dart
i have stated a lot of changes line by line please re check them all and also pull from main branch some new lints are added to enforce good coding practices

2023-10-13 06:42 UTC, dk-a-dev commented on lib/screens/home_page.dart
I expected that u would take inspiration from the colour scheme of the hacktoberfest website...
that purpleaccent on one home and blue on contributors and then again purple on info page makes it look bad

Changes Needed:
- add cont wherever necessary
- use hacktoberfest designs and colour palette to make UI changes
- Look the app at light mode and u will realise that white text colour on selection of a tab makes it look disappear please fix the colour scheme
- also change the appbar to new material app bar as its full revamp

2023-10-13 06:44 UTC, dk-a-dev commented on lib/screens/home_page.dart
Import on line 2-3 seems like unused imports added by code editor please fix them

2023-10-13 06:46 UTC, dk-a-dev commented on lib/screens/info_page.dart
>    static const color = Color(0xff13253d);
seems unused

2023-10-13 06:48 UTC, dk-a-dev commented on lib/screens/info_page.dart
- add const wherever required
- remove unused variables
- and try to improve UI of info page, try a different design as hacktoberfest image on a purple background looks bad...try taking inspiration from hacktoberfest website or some other platforms like dribble, pintrest, don't forget to stick to theme of hacktoberfesr(colours,fonts etc)

2023-10-13 06:51 UTC, dk-a-dev commented on lib/screens/search_repos.dart
>    TextEditingController _controller = TextEditingController();
add final keyword

2023-10-13 06:52 UTC, dk-a-dev commented on lib/screens/search_repos.dart
Add const wherever required

2023-10-13 06:53 UTC, dk-a-dev commented on lib/screens/search_repos.dart
> +                primary: Colors.blue, // Change button background color
![image](https://github.com/IEEE-VIT/hacktoberfest-flutter/assets/84137299/9adb6987-feab-470b-b8a0-1c94ab782066)

2023-10-13 06:53 UTC, dk-a-dev commented on lib/screens/search_repos.dart
> +                primary: Colors.blue, // Change button background color
backgroundColor: Colors.blue,

2023-10-13 06:55 UTC, dk-a-dev commented on lib/main.dart
> -  const MyApp({super.key});
this is fine, its modern way of passing keys refer concept of parent classes in dart
and modify it back to this state

2023-10-13 07:01 UTC, dk-a-dev requested changes
Good Work, but there are  a lot of changes to do please look into in b/w comments
Summary of Review:
- adopt new flutter practices
- add const wherever necessary
- remove unused code parts
- check your flutter version and work on a new one 
- use new functions and methods only avoid deprecated ones
- a commit adding linter rules is added make sure to refactor code properly as per those rules
- major UI changes required, like change in colour palette and theme also in design of info page along with of navigation rail at bottom and also of app bar on top

Please make changes

2023-10-13 08:55 UTC, shirshakk commented on lib/main.dart
in this I have  to remove the github logo and apply the hacktoberfest image?

2023-10-13 10:56 UTC, dk-a-dev commented on lib/main.dart
no just remove everything related to splash screen and keep pulling from master to keep ur project fork updated

2023-10-13 11:01 UTC, dk-a-dev commented
Hey @shirshakk i am happy to see you fixing things and making changes, but please improve your commit message and commit frequently for better commit history
refer- [conventional commit message standard](https://gist.github.com/qoomon/5dfcdf8eec66a051ecd85625518cfd13)

2023-10-14 07:03 UTC, shirshakk commented
I have made all the changes as per the requirements. on [Updated(lib/main.dart:) , please let me know if any more changes are needed to be done

2023-10-14 09:48 UTC, shirshakk commented
Hello, I've completed my work. Could you please review it and let me know if any further changes or feedback are needed? Thanks!

2023-10-14 15:48 UTC, dk-a-dev commented
@shirshakk , can u also resolve merge conflicts, if u cant le me know I will help

2023-10-14 16:10 UTC, shirshakk commented
need help to resolve merge conflicts.

2023-10-14 16:11 UTC, shirshakk commented
@dk-a-dev , Need help to resolve merge conflicts

2023-10-14 16:24 UTC, dk-a-dev commented
@shirshakk yup k don't worry I will resolve them and then review your pr, also do me a favour please pull from master and make sure optimization and refactoring is done

2023-10-14 16:51 UTC, shirshakk commented
please add hactoberfest and hactoberfest-accepted tag

2023-10-15 10:51 UTC, dk-a-dev commented
@shirshakk where are all ur commits and why us closed the PR

2023-10-15 11:03 UTC, shirshakk commented
I have not closed the PR . This is automatically closed when you resolve the merge conflict

2023-10-15 11:04 UTC, shirshakk commented
@dk-a-dev I have not closed the PR

2023-10-15 11:11 UTC, dk-a-dev commented
> I have not closed the PR . This is automatically closed when you resolve the merge conflict

No buddy how is that possible, a lot of people resolved conflicts and asked to me to merge it
something went wrong from ur end

2023-10-15 11:11 UTC, shirshakk commented
Please guide me what to do now

2023-10-15 11:27 UTC, shirshakk commented
What if i create a new PR with changes?

2023-10-18 10:31 UTC, dk-a-dev commented
@shirshakk please give progress report

2023-10-21 06:58 UTC, dk-a-dev commented
@shirshakk your conflicts are unsolvable and creating problems in master
I suggest refiling a PR on the issue, recloning would be great as this will update ur branch with master

2023-10-21 06:58 UTC, closed without merging