fixed bugs and Ui colors
IEEE-VIT/hackfest-flutter pull request #60
Opened 2023-10-14 05:14 UTC by Riktam-Santra

# Fixed numerous issues
[Change UI color to match HacktoberFest's official colors](https://github.com/IEEE-VIT/hacktoberfest-flutter/issues/59)
[About us page can't load the hacktoberfest Image](https://github.com/IEEE-VIT/hacktoberfest-flutter/issues/58)
[Contributors page throws FormatException](https://github.com/IEEE-VIT/hacktoberfest-flutter/issues/57)

## Changes made

-   made Contributors page use Uri.parse rather than Uri.https to prevent FormatException.
-   switched from SvgPicture.network to Image.network to load the hcktoberfest PNG logo on About Us page.
-   Changed colors from `0xff13253d` to `0xFF0F0913` for both Splash screen and About Us page.

## How does the solution address the problem

This PR will remove unnecessary Format and XML Parsing exceptions and make the colors for hacktoberfest blend in with the background color resulting in a more appealing UI and Smooth experience

## Linked issues

Resolves #57 #58 #59

2023-10-14 06:36 UTC, dk-a-dev commented on lib/screens/contributors.dart
Please Revert Back only including this be only fix

2023-10-14 06:36 UTC, dk-a-dev requested changes
Two issues declared duplicate
One fix to be reviewed after changes

2023-10-14 07:24 UTC, Riktam-Santra commented on lib/screens/contributors.dart
Updated the PR, reverted color changes on splash_screen and info_page

NOTE: This has also reverted the change for #58

2023-10-15 18:41 UTC, dk-a-dev approved these changes
👍

2023-10-15 18:44 UTC, merged