App flow Added
IEEE-VIT/hackfest-flutter pull request #72
Opened 2023-10-21 07:44 UTC by SarveshChavan

App flow documentation

#66 

## Changes made
appflow.md file added which shows app flow in text format.

## How does the solution address the problem
New contributors can read the appflow file and can understand the flow of the app.

2023-10-21 14:20 UTC, dk-a-dev requested changes
Fixes:
- add this to readme.md no need of a new file
- what is this:) write it properly in markdown, I can barely understand
![image](https://github.com/IEEE-VIT/hackfest-flutter/assets/84137299/54666da4-3365-4ae7-8d8b-f513ba1fd8ed)
- Some of the things like Help and Chnage theme could be changed mentioning a settings tab
- take help of gpt add improve the content and app flow

Resource:
[Markdown guide](https://www.markdownguide.org/cheat-sheet/)
For markdown syntax ref u can also check readme of this repo

2023-10-21 14:54 UTC, SarveshChavan commented
Very sorry for the mistake, I'll correct the markdown format and also add the settings tab

2023-10-21 15:07 UTC, dk-a-dev commented
@SarveshChavan le me know once u done with changes

2023-10-21 16:07 UTC, SarveshChavan commented
please review the PR again, sorry for the previous commit

2023-10-22 07:58 UTC, dk-a-dev commented on README.md
Remove that rules part,its understandable, one can understand from seeing ur format

2023-10-22 08:02 UTC, SarveshChavan commented on README.md
Ok I'll do it

2023-10-22 08:04 UTC, dk-a-dev commented on README.md
No i am doing it now
@SarveshChavan

2023-10-22 08:05 UTC, dk-a-dev commented on README.md
i will push some commits just wait

2023-10-22 08:08 UTC, SarveshChavan commented on README.md
Ok thanks 👍🏻

2023-10-23 13:58 UTC, SarveshChavan commented
@dk-a-dev please review the PR

2023-10-23 15:29 UTC, dk-a-dev commented
@SarveshChavan dw i am ur co-contributor in this issue, i will add some commit then i will consider merging it

2023-10-24 05:37 UTC, dk-a-dev requested changes
[Mermaid JS graphing in markdown](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/)

I am planning to use this js tool
give ur suggestions

2023-10-24 07:35 UTC, SarveshChavan commented on README.md
> +## App Work Flow
I think Mermaid JS is a nice option, Ill love to learn and use it. Let me know when to start the work again?

2023-10-24 15:05 UTC, dk-a-dev commented
@SarveshChavan download one extension in vscode named
> Markdown Preview Mermaid Support
> refer [Doc Mermaid.js](https://mermaid.js.org/intro/getting-started.html)
> I will be also helping u in this and learning

2023-10-24 16:18 UTC, SarveshChavan commented
@dk-a-dev I have added the app flow using mermaid js but it's not getting rendered here on GitHub but in vs code, it is visible. Check it once and let me know.

2023-10-24 17:06 UTC, SarveshChavan commented
mermaid js app flow working fine, @dk-a-dev review it when you get free

2023-10-24 17:14 UTC, dk-a-dev commented
> mermaid js app flow working fine, @dk-a-dev review it when you get free

is it renedering nicely for u now

2023-10-24 17:35 UTC, SarveshChavan commented
> > mermaid js app flow working fine, @dk-a-dev review it when you get free
> 
> is it renedering nicely for u now

yes

2023-10-24 18:00 UTC, dk-a-dev commented
@SarveshChavan 
![image](https://github.com/IEEE-VIT/hackfest-flutter/assets/84137299/3b9de008-91cf-41b4-af3d-e4f025058e61)
How is this one....??

2023-10-24 18:30 UTC, SarveshChavan commented
About us is not calling repo card, and our main objective I guess is to explain each object such as button screen and it's functioning, the diagram you made is more like flow of screen and the thing I suggest is button, widget, screen, drawer each small component.i like this design and I'll use this and remove the long description from my app flow diagram.

2023-10-25 06:56 UTC, dk-a-dev commented
About ud will cal repo cards when we will ad contributors button there

2023-10-25 08:37 UTC, SarveshChavan commented
Check the latest commit and also refer to figma. I have created the about us page let me know is it ok or not and also run ghe figma prototype and check the connection also. Once it is done check the latest app flow diagram and let me know if any changes needed.

2023-10-26 06:01 UTC, SarveshChavan commented
@dk-a-dev what's the status of this PR.

2023-10-26 06:32 UTC, dk-a-dev commented
It is still under review ur work is done I have made some changes @mintbomb27 is reviewing them and will merge it soon if it gets approved

2023-10-26 06:34 UTC, dk-a-dev commented
To keep u in the loop: I modified ur work by removing colours.making each box of the same shape and aligning the content

2023-10-29 12:02 UTC, SarveshChavan commented
What's the status of this PR.

2023-10-29 13:43 UTC, dk-a-dev commented
ye i will be merging it by tonight

2023-10-29 18:52 UTC, dk-a-dev requested changes
## Hackfest-Flutter
This app aims to simplify the process of finding repositories on GitHub, view the various contributors to the repos, and also allows the user to become a contributor to the desired project.

Kindly consider leaving a :star: if you like the repository and our organisation.


## Getting Started
* Fork it.
* Clone your forked repo and move inside it:\
`git clone https://github.com/<your-github-username>/<repo-name>.git && cd <repo-name>`

* Checkout to a new branch to work on an issue:\
`git checkout -b my-amazing-feature`

* Now you can open the project.
* Run `flutter pub get` in the project terminal and get the dependencies.
* Use `flutter run debug` to run the app in your local emulator.
* Once you're all done coding, it's time to open a PR :)
Run the following commands from the root of the project directory:
\
`git add .`\
`git commit -m "A short description about the feature."`\
`git push origin <my-amazing-feature>`

Open your forked repo in your browser and then raise a PR to the `master` branch of this repository!


## Contributing
To start contributing, check out [CONTRIBUTING.md](https://github.com/IEEE-VIT/hacktoberfest-flutter/blob/master/CONTRIBUTING.md). New contributors are always welcome to support this project. If you want something gentle to start with, check out issues labelled as `easy` or `good-first-issue`

### App Workflow
""""""
// add ```mermaid
flowchart TD;
    SplashScreen[<font size=5>Splash Screen]
    SplashScreen --> Authentication[<font size=5>Authentication Screen]
    Authentication --> HomePage[<font size=5>Home Page Screen]
    HomePage --> MenuButton[<font size=5> Drawer Widget Menu]
    MenuButton --> Home[<font size=5>Button: Home]
    MenuButton --> Profile[<font size=5>Button: User Profile]
    MenuButton --> SignOut[<font size=5>Button: Sign Out]
    MenuButton --> ChangeTheme[<font size=5>Button: Change Theme]
    HomePage --> SearchButton[<font size=5>Search prompt<br>Search Button]
    SearchButton --> RepoCards[<font size=5>Widget: Repo Cards]
    RepoCards --> RepoInfo[<font size=5>Repo Information]
    RepoCards --> DownArrow[<font size=5>Button: Down Arrow]
    RepoCards --> BookMark[<font size=5>Button: BookMark]
    DownArrow --> Visit[<font size=5> Button: Visit GitHub Page]
    Visit --> WebVisit[<font size=5> Opens GitHub Page]
    DownArrow --> Contributors[<font size=5>Button: Contributors List]
    Contributors --> ContributorsScreen[<font size=5>Contributors Screen]
    ContributorsScreen --> ContributorWidget[<font size=5>Widget: Contributor Info Cards]
    ContributorWidget --> ViewProfile[<font size=5>Button: View Profile]
    ViewProfile --> ProfilScreen[<font size=5>Contributor's Profile Page]
    ContributorWidget --> ContributorInfo[<font size=5>Contributor's Basic details]
    ContributorsScreen --> Floating[<font size=5>Button: Floating Action Button]
    Floating --> ContributorRequest[<font size=5>Requests to be <br>a contributor]
    HomePage --> BookMarkTab[<font size=5>BookMark Screen]
    BookMarkTab --> RepoCards
    HomePage --> AboutUsTab[<font size=5>About Us Screen]
    AboutUsTab --> IEEE-VIT-Repos[<font size=5>IEEE-VIT Repo's]
    IEEE-VIT-Repos --> RepoCards
    AboutUsTab --> Visit-IEEE-VIT[<font size=5>Button: Visit IEEE GitHub]
    AboutUsTab --> Contributors-IEEE-VIT[<font size=5>Button: Hackfest App Contributors ]
// add ```

## License
This project is licensed under [<font size=5>MIT](https://github.com/IEEE-VIT/hacktoberfest-flutter/blob/master/LICENSE)

> [NOTE!]  
> This project is not officially affiliated with DigitalOcean or Hacktoberfest in any manner.

2023-10-29 18:53 UTC, dk-a-dev commented
@SarveshChavan just replace ur read me completely with above sent one and I will merge this PR

2023-10-30 04:55 UTC, dk-a-dev commented
@SarveshChavan replace md asap i have to merge this one

2023-10-30 07:20 UTC, SarveshChavan commented
share the markdown file this is a preview file unable to add in readme.md

2023-10-30 07:29 UTC, dk-a-dev requested changes
Add licesnse and not below app workflow refer shared markdown

2023-10-30 07:30 UTC, dk-a-dev commented
> share the markdown file this is a preview file unable to add in readme.md
@SarveshChavan 
I was not able to share as preview, nvm
u figured it out

2023-10-30 07:35 UTC, SarveshChavan commented
done

2023-10-30 07:55 UTC, dk-a-dev approved these changes
Good job merging
if it do not render,i will try to fix it but if fixing also doesn't work the PR might get dropped

2023-10-30 07:56 UTC, merged